name: Fábrica Universal Android

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: 'Nome do Pacote'
        required: true
      package_version:
        description: 'Versão'
        required: true
      python_version:
        description: 'Versão Python (ex: 3.12)'
        required: true
        default: '3.12'

jobs:
  build:
    name: Build ${{ inputs.package_name }}
    runs-on: ubuntu-latest
    env:
      ANDROID_API: 24
      TARGET: aarch64-linux-android
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Setup Rust & NDK
        run: |
          rustup target add ${{ env.TARGET }}
          pip install maturin
          NDK=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          echo "CC_aarch64_linux_android=$NDK/aarch64-linux-android${{ env.ANDROID_API }}-clang" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$NDK/aarch64-linux-android${{ env.ANDROID_API }}-clang" >> $GITHUB_ENV

      - name: Build Wheel
        run: |
          pip download --no-binary :all: --no-deps ${{ inputs.package_name }}==${{ inputs.package_version }}
          tar -xvf *.tar.gz --one-top-level=src_code --strip-components=1
          cd src_code
          # AQUI ESTÁ O SEGREDO: --interpreter força a compatibilidade com seu Termux
          maturin build --release --target ${{ env.TARGET }} --out ../dist --interpreter python${{ inputs.python_version }}

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-artifact   # Nome fixo para facilitar o script local
          path: dist/*.whl
